---
title: Matrix cookbook - determinant
date: 2019-10-11
tags: [Matrix, cookbook, determinant]
---

\begin{equation}
\tag{18}
\operatorname{det}(\mathbf{A})=\prod_{i} \lambda_{i} \quad \lambda_{i}=\operatorname{eig}(\mathbf{A})
\end{equation}

\begin{equation}
\tag{19}
\operatorname{det}(c \mathbf{A})=c^{n} \operatorname{det}(\mathbf{A}), \quad \text { if } \mathbf{A} \in \mathbb{R}^{n \times n}
\end{equation}

\begin{equation}
\tag{20}
\operatorname{det}\left(\mathbf{A}^{T}\right)=\operatorname{det}(\mathbf{A})
\end{equation}

---

\begin{equation}
\tag{21}
\operatorname{det}(\mathbf{A B})=\operatorname{det}(\mathbf{A}) \operatorname{det}(\mathbf{B})
\end{equation}

The determinant of a tranformation matrix is the scale of area/volume of the shape before and after the tranformation. $\mathbf{A B}$ are two consecutive transformations, therefore its determinant is the product of two scales.

---

\begin{equation}
\tag{22}
\operatorname{det}\left(\mathbf{A}^{-1}\right)=1 / \operatorname{det}(\mathbf{A})
\end{equation}

\begin{equation}
\tag{23}
\operatorname{det}\left(\mathbf{A}^{n}\right)=\operatorname{det}(\mathbf{A})^{n}
\end{equation}

---

\begin{equation}
\tag{24}
\operatorname{det}\left(\mathbf{I}+\mathbf{u v}^{T}\right)=1+\mathbf{u}^{T} \mathbf{v}
\end{equation}

---