---
title: Derivative of inverse matrix
date: 2019-10-24
tags: [matrix, derivative]
---

\begin{equation}
\tag{40}
\partial\left(\mathbf{X}^{-1}\right)=-\mathbf{X}^{-1}(\partial \mathbf{X}) \mathbf{X}^{-1}
\end{equation}

> **Explanation**: [^1]
 
\begin{equation}
\underbrace{(I)^{\prime}}_{=0}=\left(\mathbf{X} \mathbf{X}^{-1}\right)^{\prime}=\mathbf{X}^{\prime} \mathbf{X}^{-1}+\mathbf{X}\left(\mathbf{X}^{-1}\right)^{\prime} \Rightarrow
\end{equation}

\begin{equation}
\mathbf{X}\left(\mathbf{X}^{-1}\right)^{\prime}=-\mathbf{X}^{\prime} \mathbf{X}^{-1} \quad \Rightarrow
\end{equation}

\begin{equation}
\left(\mathbf{X}^{-1}\right)^{\prime}=-\mathbf{X}^{-1} \mathbf{X}^{\prime} \mathbf{X}^{-1}
\end{equation}

[^1]: https://math.stackexchange.com/questions/1471825/derivative-of-the-inverse-of-a-matrix

---

\begin{equation}
\tag{41}
\partial(\operatorname{det}(\mathbf{X}))=\operatorname{Tr}(\operatorname{adj}(\mathbf{X}) \partial \mathbf{X})
\end{equation}

## Background

### Adjugate Matrix

The adjugate of $A$ is the transpose of the cofactor matrix $C$ of $X$,
\begin{equation}
\operatorname{adj}(\mathbf{X})=\mathbf{C}^{\top}
\end{equation}

and,
\begin{equation}
\mathbf{X}^{-1}=\operatorname{det}(\mathbf{X})^{-1} \operatorname{adj}(\mathbf{X}) \quad \Rightarrow
\end{equation}

\begin{equation}
\operatorname{det}(\mathbf{X}) \mathbf{I} = \operatorname{adj}(\mathbf{X}) \mathbf{X}
\end{equation}

### Characteristic Polynomial

<p class=notes>
The characteristic polynomial of a square matrix is a polynomial which is invariant under matrix similarity and has the eigenvalues as roots. It has the determinant and the trace of the matrix as coefficients.
</p>

The characteristic polynomial of a sqaure matrix $A$ is defined by
\begin{equation}
p_{A}(t)=\operatorname{det}(t I-A)
\end{equation}

## Proof [^2]

### Via Matrix Computation

\begin{equation}
\frac{\partial \operatorname{det}(\mathbf{X})}{\partial \mathbf{X}_{i j}}=\sum_{k} \operatorname{adj}^{\mathrm{T}}(\mathbf{X})_{i k} \delta_{j k}=\operatorname{adj}^{\mathrm{T}}(\mathbf{X})_{i j} \quad \Rightarrow
\end{equation}

\begin{equation}
d(\operatorname{det}(\mathbf{X}))=\sum_{i} \sum_{j} \operatorname{adj}^{\mathrm{T}}(\mathbf{X})_{i j} d \mathbf{X}_{i j} \quad \Rightarrow
\end{equation}

\begin{equation}
d(\operatorname{det}(\mathbf{X}))=\operatorname{tr}(\operatorname{adj}(\mathbf{X}) d \mathbf{X})
\end{equation}

### Via Chain Rule

**Lemma 1.** $\operatorname{det}^{\prime}(I)=\operatorname{tr}$, where $\operatorname{det}^{\prime}$ is the differential of $\operatorname{det}$.

**Lemma 2.** For an invertible matrix $\mathbf{A}$, we have: $\operatorname{det}^{\prime}(\mathbf{A})(\mathbf{T})=\operatorname{det} \mathbf{A} \operatorname{tr}(\mathbf{A}^{-1}\mathbf{T}))$

[^2]: https://en.wikipedia.org/wiki/Jacobi%27s_formula#Derivation

---

\begin{equation}
\tag{42}
\partial(\operatorname{det}(\mathbf{X}))=\operatorname{det}(\mathbf{X}) \operatorname{Tr}\left(\mathbf{X}^{-1} \partial \mathbf{X}\right)
\end{equation}
